version: 2
updates:
  # For npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"

  # For Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

  # For Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/assb"
    schedule:
      interval: "daily"
