services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  mysql:
    image: mysql:9.1.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root307
      MYSQL_DATABASE: aipower
      MYSQL_USER: aipower_user
      MYSQL_PASSWORD: aipower_password
    volumes:
      - mysql-data:/var/lib/mysql

  aipower:
    build: ./  # Adjust if your Dockerfile is located elsewhere
    image: aipower:latest
    container_name: aipower
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - zookeeper
      - mysql
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aipower?useSSL=false
      SPRING_DATASOURCE_USERNAME: aipower_user
      SPRING_DATASOURCE_PASSWORD: aipower_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL5Dialect
      SPRING_APPLICATION_JSON: '{"spring.kafka.consumer.group-id":"aipower-group"}'
      SPRING_APPLICATION_NAME: aipower
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_CLOUD_STREAM_KAFKA_BINDER_CLIENT_ID: aipower-stream-binder
      SPRING_CLOUD_STREAM_KAFKA_BINDER_CONSUMER_GROUP_ID: my-group-consumer
      SPRING_CLOUD_STREAM_KAFKA_BINDER_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_CLOUD_STREAM_KAFKA_BINDER_PRODUCER_VALUE_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_CLOUD_STREAM_KAFKA_BINDER_PRODUCER_ACKS: all

volumes:
  mysql-data:
