name: Build and Deploy AiPower App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (for frontend)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Step 3: Install frontend dependencies and build frontend
      - name: Install Frontend Dependencies and Build
        working-directory: ./frontend  # Adjust path if necessary
        run: |
          npm install
          npm run build

      # Step 4: Set up Java (for backend)
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '23'  # Change to your preferred LTS version
          distribution: 'adopt'

      # Step 5: Build the Java Spring Boot backend
      - name: Build Java Backend (Spring Boot)
        working-directory: ./backend  # Adjust path if necessary
        run: ./gradlew build

      # Step 6: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Step 7: Deploy Frontend to Google Cloud Storage
      - name: Deploy Frontend to Google Cloud Storage
        run: |
          gsutil -m cp -r ./frontend/build/* gs://$GCP_BUCKET_NAME/
        env:
          GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}

      # Step 8: Deploy Backend to Google App Engine
      - name: Deploy Backend to Google App Engine
        run: |
          gcloud app deploy ./aipower.yaml --project $GCP_PROJECT_ID --quiet
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      # Optional: Additional Deployment Targets
      # Uncomment these steps as needed for GKE or Compute Engine
