name: Aipower Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Aipower Docker Image
      run: |
        docker-compose build
        docker-compose push

    - name: Test Aipower Docker Image
      run: |
        docker-compose up -d
        docker-compose ps

    - name: Shut Down Docker Containers
      run: docker-compose down
