name: Aipower Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest

    - name: Navigate to Frontend Directory and Install Dependencies
      working-directory: ./frontend
      run: npm install --no-audit --no-fund

    - name: Install Webpack CLI
      working-directory: ./frontend
      run: npm install -D webpack-cli

    - name: Build the Frontend
      working-directory: ./frontend
      run: npm run build

    - name: Test the Frontend
      working-directory: ./frontend
      run: npm test
